
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layout/Header";

const roboto = Roboto({ subsets: ["latin"] , weight:['400','500','700']});

export const metadata=   {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-8xl mx-20 my-5 ">
        <Header/>{children} 
            <footer className=" relative top-80 border-t p-8 text-center text-gray-500 mt-16">

&copy; 2023 All rights reserved
</footer></main></body>
    </html>
  );
}
